### ISSUE TITLE
segmentation fault on success build 

### ISSUE THREAD

**Issue by equisde** [loki-project/loki#331]
hello i was able to compile windows binary but when i try to excecute the binary it inmediately ask to force close and in mingw shell excecuting ./lokid i get segmentation fauls as in the following pict

![image](https://user-images.githubusercontent.com/34652149/48751358-b1e00980-ec62-11e8-89e6-74c6d95113c9.png)
i'm using the 64bit version of mingw and compiled the 64bit version of loki

**Comment by Doy-lee** [comment]
Did you set `USE_SINGLE_BUILDDIR=1`? If you didn't then you're building the old version because you won't be generating binaries in build/release/bin if you're on the latest version by default unless you set the aforementioned flags.

**Comment by equisde** [comment]
thanks for your reply i tried what you said but i get the same problem

**Comment by Doy-lee** [comment]
Well unfortunately I am not sure what the problem is here, I'm going to need more information. The first step would be to build debug binaries and drop a stack trace or core dump. Information is available in the readme, debug builds can be made using `make debug-static-win64`.

**Comment by equisde** [comment]
hello i was trying to build binaries from another computer but unfortunatelly i got error with zlib since i got errors with openssl 1.1 i tried to downgrade from msys with pacman -U openssl package  but it breaks other libs and cmake is unable to run one of those libs is zlib i tried with almost all packages but with no luck and when i try to build with openssl i get this error



```
[  7%] Building C object external/unbound/CMakeFiles/unbound.dir/validator/val_secalgo.c.obj
C:/Users/Administrador.WIN-UVEASD8J3LC/Desktop/sevabit-new-master/external/unbound/validator/val_secalgo.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*
 ^
C:/Users/Administrador.WIN-UVEASD8J3LC/Desktop/sevabit-new-master/external/unbound/validator/val_secalgo.c: In function 'verify_canonrrset':
C:/Users/Administrador.WIN-UVEASD8J3LC/Desktop/sevabit-new-master/external/unbound/validator/val_secalgo.c:651:35: error: dereferencing pointer to incomplete type 'EVP_MD_CTX {aka struct evp_md_ctx_st}'
  ctx = (EVP_MD_CTX*)malloc(sizeof(*ctx));
                                   ^
C:/Users/Administrador.WIN-UVEASD8J3LC/Desktop/sevabit-new-master/external/unbound/validator/val_secalgo.c:667:3: warning: implicit declaration of function 'EVP_MD_CTX_cleanup' [-Wimplicit-function-declaration]
   EVP_MD_CTX_cleanup(ctx);
   ^
make[3]: * [external/unbound/CMakeFiles/unbound.dir/build.make:817: external/unbound/CMakeFiles/unbound.dir/validator/val_secalgo.c.obj] Error 1
make[3]: se sale del directorio '/c/Users/Administrador.WIN-UVEASD8J3LC/Desktop/sevabit-new-master/build/release'
make[2]: * [CMakeFiles/Makefile2:210: external/unbound/CMakeFiles/unbound.dir/all] Error 2
make[2]: se sale del directorio '/c/Users/Administrador.WIN-UVEASD8J3LC/Desktop/sevabit-new-master/build/release'
make[1]: * [Makefile:129: all] Error 2
make[1]: se sale del directorio '/c/Users/Administrador.WIN-UVEASD8J3LC/Desktop/sevabit-new-master/build/release'
make: * [Makefile:147: release-static-win64] Error 2
```
and when i try to run cmake 


```
$ cmake 
C:/msys64/mingw64/bin/cmake.exe: error while loading shared libraries: zlib1.dll : cannot open shared object file: No such file or directory
```
--





any clue on how to fix it?

**Comment by Doy-lee** [comment]
Cmake error is because you're messing with the build environment and manually downgrading components. That is out of the scope of support we can give as we only build against the latest MSYS packages.

Again you are using an old version of the repository. This is fixed in the latest https://github.com/monero-project/monero/issues/4493

**Comment by equisde** [comment]
it's weird because i did  git submodule update but still can't compile i installed all msys packages from 0 but it did not work still the same error with openssl

**Comment by KeeJef** [comment]
If there is no update on this i will close this issue
